# Generated by Django 2.1.7 on 2019-03-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixapi', '0003_webhook_webhookcall_webhookeventlistener'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookcall',
            options={'ordering': ('-datetime',)},
        ),
        migrations.AlterModelOptions(
            name='webhookeventlistener',
            options={'ordering': ('action_type',)},
        ),
    ]
